# Generated by Django 4.2.5 on 2023-09-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdetails',
            old_name='news_object',
            new_name='newsobject',
        ),
    ]
