# Generated by Django 4.2.5 on 2023-09-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_news_object_newsdetails_newsobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости '},
        ),
    ]
