# Generated by Django 4.2.5 on 2023-10-07 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_rename_admins_admi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admi',
            new_name='Admins',
        ),
    ]
